import fs from "node:fs";
import path from "node:path";
import { marked } from "marked";

/**
 * Posts for /writing.
 *
 * The Markdown in `content/writing/` is generated by `scripts/sync-writeups.py` from
 * the canonical `writeups` repository, so this module only reads what is already
 * committed. Nothing here fetches anything at build time — a build that depends on
 * the network fails for reasons that have nothing to do with the site.
 */

const DIR = path.join(process.cwd(), "content", "writing");

export type PostMeta = {
  slug: string;
  title: string;
  date: string;
  summary: string;
  source: string;
  words: number;
  minutes: number;
};

export type Post = PostMeta & { html: string };

function parseFrontmatter(raw: string): { meta: Record<string, string>; body: string } {
  const match = /^---\n([\s\S]*?)\n---\n?/.exec(raw);
  if (!match) return { meta: {}, body: raw };
  const meta: Record<string, string> = {};
  for (const line of match[1].split("\n")) {
    const idx = line.indexOf(":");
    if (idx === -1) continue;
    meta[line.slice(0, idx).trim()] = line.slice(idx + 1).trim();
  }
  return { meta, body: raw.slice(match[0].length) };
}

function readingMinutes(body: string): number {
  // 200 words per minute, floored at 1 so a short note never reads as "0 min".
  return Math.max(1, Math.round(body.split(/\s+/).filter(Boolean).length / 200));
}

export function getPosts(): PostMeta[] {
  if (!fs.existsSync(DIR)) return [];
  return fs
    .readdirSync(DIR)
    .filter((f) => f.endsWith(".md"))
    .map((file) => {
      const raw = fs.readFileSync(path.join(DIR, file), "utf-8");
      const { meta, body } = parseFrontmatter(raw);
      const words = body.split(/\s+/).filter(Boolean).length;
      return {
        slug: file.replace(/\.md$/, ""),
        title: meta.title ?? file.replace(/\.md$/, ""),
        date: meta.date ?? "",
        summary: meta.summary ?? "",
        source: meta.source ?? "",
        words,
        minutes: readingMinutes(body),
      };
    })
    .sort((a, b) => (a.date < b.date ? 1 : a.date > b.date ? -1 : 0));
}

export function getPost(slug: string): Post | null {
  const file = path.join(DIR, `${slug}.md`);
  if (!fs.existsSync(file)) return null;
  const raw = fs.readFileSync(file, "utf-8");
  const { meta, body } = parseFrontmatter(raw);
  const words = body.split(/\s+/).filter(Boolean).length;
  return {
    slug,
    title: meta.title ?? slug,
    date: meta.date ?? "",
    summary: meta.summary ?? "",
    source: meta.source ?? "",
    words,
    minutes: readingMinutes(body),
    html: marked.parse(body, { async: false }) as string,
  };
}

export function formatDate(iso: string): string {
  if (!iso) return "";
  const d = new Date(`${iso}T00:00:00Z`);
  if (Number.isNaN(d.getTime())) return iso;
  return d.toLocaleDateString("en-GB", {
    day: "numeric",
    month: "long",
    year: "numeric",
    timeZone: "UTC",
  });
}

/**
 * The social preview card for a post, or the site default.
 *
 * Cards are rendered at build time by `scripts/make-og-images.py`, so a newly
 * written post has no card until that runs. Returning the shared default in that
 * case is deliberate: a preview image pointing at a path that does not exist is a
 * broken card, which is worse than a generic one.
 */
export function ogImageFor(slug: string): string {
  const card = path.join(process.cwd(), "public", "og", `${slug}.png`);
  return fs.existsSync(card) ? `/og/${slug}.png` : "/og.png";
}
