#!/usr/bin/env python3
"""Fail the build when a post would render without a title, or share without a card.

Why this exists
---------------
A post whose source used YAML frontmatter instead of the house `# Title` format
synced with an EMPTY title. The site built successfully, deployed, and served a
post page with an empty `<h1>` and an empty `og:title` — the two things a reader
and a search engine each use to decide what the page is. Nothing objected, because
a missing heading is not a build error.

That is the failure mode this repository's sibling `reputation` project exists to
prevent: a check that quietly found nothing is indistinguishable from everything
being fine. So this runs as `prebuild`, and it exits non-zero rather than warning.

Why the social card is checked here too
---------------------------------------
The cards in `public/og/` are generated by `scripts/make-og-images.py` and
committed — a build never depends on that having run. The consequence is that a new
post does not get a card unless someone runs the generator, and nothing said so: the
post shipped advertising the generic `/og.png`, identical to every other post in a
timeline. That is the same defect as a stale index — a row that no longer exists
beside a check that only reads the rows that do.

What it checks
--------------
Structural, not editorial. Every synced post must carry a non-empty `title`,
`date` and `summary` in its frontmatter — the three fields the page renders or
advertises — and must have a card at `public/og/<slug>.png`. A card with no post is
reported too, so a renamed post cannot leave its old card behind looking current.
It does not judge the writing, the length, or the accuracy, because those are not
things a script should decide.

Deliberately NOT checked: whether the title matches the source's H1. The synced
copy is generated, so a mismatch means the sync ran with different input, and the
generator is the place to fix that.

    python3 scripts/check-posts.py
    python3 scripts/check-posts.py --self-test
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
POSTS = ROOT / "content" / "writing"
OG = ROOT / "public" / "og"

REQUIRED = ("title", "date", "summary")


def frontmatter(raw: str) -> dict[str, str]:
    """The same shape `src/lib/writing.ts` parses, so the two cannot disagree."""
    match = re.match(r"^---\n(.*?)\n---\n?", raw, re.S)
    if not match:
        return {}
    meta: dict[str, str] = {}
    for line in match.group(1).split("\n"):
        idx = line.find(":")
        if idx == -1:
            continue
        meta[line[:idx].strip()] = line[idx + 1:].strip()
    return meta


def audit(found: dict[str, dict[str, str]], cards: set[str]) -> list[str]:
    """Problems with the posts and their cards. Pure, so --self-test can call it."""
    problems: list[str] = []
    for slug, meta in sorted(found.items()):
        if not meta:
            problems.append(f"{slug}.md: no frontmatter block")
            continue
        for field in REQUIRED:
            if not meta.get(field, "").strip():
                problems.append(f"{slug}.md: empty or missing {field!r}")
        if f"{slug}.png" not in cards:
            problems.append(f"{slug}.md: no social card at public/og/{slug}.png")
    for card in sorted(cards - {f"{slug}.png" for slug in found}):
        problems.append(f"public/og/{card}: no post with that slug")
    return problems


def self_test() -> int:
    """Prove both checks fire, and that a clean set stays quiet.

    The failure mode of every guard here is silence, so each check is fed the exact
    shape of the defect it exists for and required to report it.
    """
    post = {"title": "A title", "date": "2026-09-24", "summary": "A summary"}
    cases = [
        ("a well-formed post with its card is clean",
         {"ok": post}, {"ok.png"}, False),
        ("an empty title is caught",
         {"bad": {**post, "title": ""}}, {"bad.png"}, True),
        ("a missing frontmatter block is caught",
         {"bad": {}}, {"bad.png"}, True),
        ("a post with no card is caught",
         {"nocard": post}, set(), True),
        ("a card with no post is caught",
         {"solo": post}, {"solo.png", "orphan.png"}, True),
    ]

    failures = 0
    for label, found, cards, expect in cases:
        detected = bool(audit(found, cards))
        ok = detected == expect
        print(f"  {'ok  ' if ok else 'FAIL'}  {label}")
        if not ok:
            failures += 1

    if failures:
        print(f"\n{int(failures)} self-test case(s) behaved wrongly. The guard is not "
              "guarding; do not trust a pass from it.", file=sys.stderr)
        return 1
    print("\nself-test: every check fires on the defect it exists for, and a clean "
          "set stays quiet")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--self-test", action="store_true",
                        help="prove the checks fire, using synthetic fixtures")
    args = parser.parse_args()

    if args.self_test:
        return self_test()

    if not POSTS.is_dir():
        print(f"no posts directory at {POSTS}", file=sys.stderr)
        return 1

    paths = sorted(POSTS.glob("*.md"))
    if not paths:
        print("no posts found — a build with nothing to check is not a pass", file=sys.stderr)
        return 1

    found = {p.stem: frontmatter(p.read_text(encoding="utf-8")) for p in paths}
    cards = {c.name for c in OG.glob("*.png")} if OG.is_dir() else set()

    problems = audit(found, cards)

    if problems:
        print(f"{len(problems)} post problem(s) — refusing to build:\n", file=sys.stderr)
        for problem in problems:
            print(f"  {problem}", file=sys.stderr)
        print(
            "\nA post source in sushant-me/writeups uses '# Title' plus a byline line;"
            "\nthe sync copies it here. YAML frontmatter in the source produces an"
            "\nempty title, which renders as an empty <h1> and og:title."
            "\n\nA missing card is generated with:"
            "\n  uv run --with pillow python3 scripts/make-og-images.py"
            "\nThe generated PNGs are committed, so this must be run before a push.",
            file=sys.stderr,
        )
        return 1

    print(f"{len(found)} posts checked: title, date and summary present, "
          f"{len(found)} card(s) present")
    return 0


if __name__ == "__main__":
    sys.exit(main())
